name: Version check

on:
  pull_request:
    branches:
      - stage/*
      - prod/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        shell: bash
        run: |
          VERSION=$(str=${{ github.head_ref }};  echo ${str#*/})
          [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+[\-a-z0-9]*$ ]] || exit 1
      