name: Deploy
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Version to deploy
        required: true
      env:
        required: true
        type: choice
        description: Environemnt to deploy to
        options:
          - stage
          - prod

jobs:
  make-deploy-pr:
    name: "Creating Deploy PR"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check version
        shell: bash
        run: |
          export version=${{ github.event.inputs.release-version }}
          [[ $version =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && exit 0 || exit 1

      - name: Checkout previous deployment
        id: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.inputs.env }}/latest
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Creating branch 
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          LATEST=${{ github.event.inputs.env }}/latest
          VERSION=${{ github.event.inputs.release-version }}
          ENV=${{ github.event.inputs.env }}
          
          git fetch origin
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # creating base brunch for PR
          git checkout -b $ENV/$VERSION
          git push origin $ENV/$VERSION

          # creting PR branch based on version tag
          git checkout -b $ENV-deploy/$VERSION $VERSION
          git push origin $ENV-deploy/$VERSION

          CHANGES=$(git log $LATEST..HEAD --pretty=format:"%h - %s (%an, %ad)")
          gh pr create --base $ENV/$VERSION --title "[$VERSION] ${ENV^} deployment" --body "$CHANGES"
