name: Require Members Approval

on:
  pull_request:
    branches:
      - dev
      - stage/*
      - prod/*
  pull_request_review:
    types: [edited, submitted, dismissed]
    branches:
      - dev
      - stage/*
      - prod/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  require-members-approval:
    name: "Approval"
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR data
        shell: bash
        run: |
          PRBRANCH=${{ github.head_ref }}
          echo "branch="$(str=${{ github.event.pull_request.base.ref}}; echo ${str%%/*}) >> $GITHUB_OUTPUT
          echo "hotfix_suffix="$([[ $PRBRANCH =~ hotfix.*?$ ]] && echo "-hotfix" || echo "") >> $GITHUB_OUTPUT
        id: data

      - name: Check
        uses: creotiv/custom-approval-management@v0.0.4
        with:
          token: ${{ secrets.PAT }}
          config: .github/configs/${{ steps.data.outputs.branch }}/approval${{ steps.data.outputs.hotfix_suffix }}.yml
