name: 'Auto Assign Reviewers'
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - dev
      - stage/*
      - prod/*

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    name: "Assigning"
    steps:
      - name: Extract branch name
        shell: bash
        env:
          GITHUB_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: echo "branch=${GITHUB_BRANCH}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/configs/${{ steps.extract_branch.outputs.branch }}/assign.yml
