name: Require Members Approval

on:
  pull_request:
    branches:
      - dev
      - stage
      - prod
  pull_request_review:
    types: [edited, submitted, dismissed]
    branches:
      - dev
      - stage
      - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  require-members-approval:
    name: "Approval"
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: creotiv/custom-approval-management@v0.0.4
        with:
          token: ${{ secrets.PAT }}
          config: .github/configs/${{ steps.extract_branch.outputs.branch }}/approval.yml
