name: Deploy branch
on:
  push:
    branches:
      - dev

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          fi
        id: extract_branch

      - name: Exit on direct Push
        run: |
          echo $GITHUB_EVENT_PATH
          echo ${{github.ref}}
          echo ${{ steps.extract_branch.outputs.branch }}
          echo "Push made not from PR. Exiting"
          exit 1

      - name: Build on PR
        run: |
          echo ${{ steps.extract_branch.outputs.branch }}
          echo "Running push from PR"
